# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0002_employee_is_approver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approver', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='home_department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_approver',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Department'),
        ),
        migrations.AddField(
            model_name='departmentemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Employee'),
        ),
    ]
