# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0003_auto_20160223_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_workday', models.BooleanField()),
                ('day_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Day_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Day')),
                ('day_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Day_Type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Employee')),
            ],
        ),
        migrations.RenameField(
            model_name='departmentemployee',
            old_name='departments',
            new_name='department',
        ),
    ]
