# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0004_auto_20160223_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annual_Leave_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('max_annual_leave', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Annual_Leave_Category'),
            preserve_default=False,
        ),
    ]
