# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0005_auto_20160223_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annual_leave_category',
            options={'verbose_name': 'Annual Leaving Category', 'verbose_name_plural': 'Annual Leaving Categories'},
        ),
        migrations.AlterModelOptions(
            name='day_type',
            options={'verbose_name': 'Day Type', 'verbose_name_plural': 'Day Types'},
        ),
        migrations.AlterField(
            model_name='employee_day',
            name='day',
            field=models.DateField(),
        ),
    ]
