# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0007_auto_20160318_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('lapse_days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Employee')),
                ('event_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Day_Type')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employee_day',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='employee_day',
            name='day_Type',
        ),
        migrations.RemoveField(
            model_name='employee_day',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee_Day',
        ),
    ]
