# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0010_employee_event_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_event',
            name='approver_display_color',
            field=models.CharField(default='#00ff00', max_length=10),
            preserve_default=False,
        ),
    ]
