# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0011_employee_event_approver_display_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_event',
            name='approver_display_color',
        ),
    ]
