# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0012_remove_employee_event_approver_display_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_event',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='vacantpie.Employee'),
        ),
        migrations.AddField(
            model_name='employee_event',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_event',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decliner', to='vacantpie.Employee'),
        ),
        migrations.AddField(
            model_name='employee_event',
            name='delcined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_event',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_event',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='vacantpie.Employee'),
        ),
    ]
