# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0013_auto_20160331_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_event',
            old_name='delcined_date',
            new_name='declined_date',
        ),
    ]
