# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0015_day_type_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Leave Categories',
                'verbose_name': 'Leave Category',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='annual_leave_category',
        ),
        migrations.DeleteModel(
            name='Annual_Leave_Category',
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Leave_Category'),
            preserve_default=False,
        ),
    ]
