# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0016_auto_20160413_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Category_Max_Day_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days', models.IntegerField(default=365)),
                ('day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Day_Type')),
                ('leave_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantpie.Leave_Category')),
            ],
        ),
    ]
