# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantpie', '0017_leave_category_max_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_type',
            name='is_default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
